# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Restroom.create(business_name: =>'Cheescake Factory', description: => "Finding that Los Angeles loved their cheesecakes as much as Detroit, their reputation and sales grew, creating a need for a larger bakery. 1975 marked the beginning of the most creative and productive period of their business endeavors. With their new and improved bakery, Evelyn created over 20 varieties of her delicious cheesecakes and other fantastic desserts, which were sold to hundreds of wholesale accounts. Oscar purchased delivery trucks, hired drivers, expanded their cheesecake distribution from Santa Barbara to San Diego and developed additional out-of-state customers. Their tireless efforts, commitment to quality and innovative product development laid the foundation for The Cheesecake Factory's future success.")
Restroom.create(business_name: 'The Melting Pot', description: "Finding that Los Angeles loved their cheesecakes as much as Detroit, their reputation and sales grew, creating a need for a larger bakery. 1975 marked the beginning of the most creative and productive period of their business endeavors. With their new and improved bakery, Evelyn created over 20 varieties of her delicious cheesecakes and other fantastic desserts, which were sold to hundreds of wholesale accounts. Oscar purchased delivery trucks, hired drivers, expanded their cheesecake distribution from Santa Barbara to San Diego and developed additional out-of-state customers. Their tireless efforts, commitment to quality and innovative product development laid the foundation for The Cheesecake Factory's future success.")
Restroom.create(business_name: 'Smith and Wollensky', description: "A prime spotting place for local celebrities, political figures and even a few movie stars, Smith & Wollensky has long been considered a premier dining destination. Offering simple elegant food, attention to detail in service, a refined setting, the experience is uniquely American—and says unequivocally “YOU’VE ARRIVED™.” Our signature green and white building was established in 1977 in New York. Today, with nine boutique and distinctively different locations, it continues to symbolize the timeless luxury of Prime USDA steaks, premium seafood, signature cocktails and award-winning wines. We’re still the only national steakhouse to dry-age and butcher on site, fly in fresh lobster daily and make our sides and pastries by hand. Our staff put your comfort and pleasure as their absolute priority. So whether you visit for an intimate gathering or large celebration, you’ll be glad when you’ve arrived.")
Restroom.create(business_name: 'Northstar Cafe', description: "The Northstar Café was established in 2004 and inspired by the eclectic energy of downtown Columbus, Ohio. Our carefully prepared yet casual cuisine and our unique urban ambience have earned a stream of loyal fans. The clean lines and fresh colors of Northstar reflect our sincere commitment to pure and natural dining, rooted in our Ohio soil. The Café features an imaginative menu of New American cuisine with a healthful emphasis on organic ingredients. Our display kitchen and in-house bakery are open to the dining room to reveal that fine, prepared from scratch food can be just as enjoyable during a quick breakfast meeting as during a relaxing dinner date. Whether you're in the mood for a warm scone and a mug of the richest organic coffee in town, or you're ready for a frosty micro-brew and an appetizer, we look forward to serving you.")
